/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.group4.risc.client;

import edu.duke.ece651.group4.risc.shared.Territory;
import java.net.*;
import java.io.*;
import java.util.ArrayList;

public class Client {
  public static void main(String[] args) throws ClassNotFoundException {
    String serverName = "localhost";
    int port = 6066;
    try {
      System.out.println("Connecting to " + serverName + " on port " + port);
      Socket client = new Socket(serverName, port);
      System.out.println("Just connected to " + client.getRemoteSocketAddress());
      /*
       * DataOutputStream out = new DataOutputStream(client.getOutputStream());
       * DataInputStream in = new DataInputStream(client.getInputStream());
       * out.writeUTF("Hello from " + client.getLocalSocketAddress());
       * System.out.println("Server says " + in.readUTF());
       */
      ObjectOutputStream os = new ObjectOutputStream(client.getOutputStream());
      ObjectInputStream is = new ObjectInputStream(new BufferedInputStream(client.getInputStream()));

      // receive an object from server
      Object obj = is.readObject();

      if (obj != null) {
        ArrayList<Integer> arr = (ArrayList<Integer>) obj;
        for (int i = 0; i < arr.size(); i++) {
          System.out.print(arr.get(i) + " ");
        }
        System.out.print("\n");
      }

      os.close();
      is.close();
      client.close();
      /*
       * out.close(); in.close();
       */
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  // }
}
