/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.group4.risc.client;

import edu.duke.ece651.group4.risc.shared.Map;
import edu.duke.ece651.group4.risc.shared.Player;
import edu.duke.ece651.group4.risc.shared.Territory;
import edu.duke.ece651.group4.risc.shared.TextPlayer;
import java.net.*;
import java.io.*;
import java.util.ArrayList;

public class Client {
  public static void main(String[] args) throws ClassNotFoundException {
    String serverName = "localhost";
    int port = 6066;
    try {
      System.out.println("Connecting to " + serverName + " on port " + port);
      Socket client = new Socket(serverName, port);
      System.out.println("Just connected to " + client.getRemoteSocketAddress());
      /*
       * DataOutputStream out = new DataOutputStream(client.getOutputStream());
       * DataInputStream in = new DataInputStream(client.getInputStream());
       * out.writeUTF("Hello from " + client.getLocalSocketAddress());
       * System.out.println("Server says " + in.readUTF());
       */
      ObjectOutputStream os = new ObjectOutputStream(client.getOutputStream());
      ObjectInputStream is = new ObjectInputStream(new BufferedInputStream(client.getInputStream()));

      // receive an object from server
      Object obj_map = is.readObject();
      Object obj_id = is.readObject();

      if (obj_map != null && obj_id != null) {
        Map<Character> map = (Map<Character>) obj_map;
        Integer player_id = (Integer) obj_id;
        MapTextView displayInfo = new MapTextView(map, System.out);
        displayInfo.displayCurrentMap();
        displayInfo.displayPlayerMsg(player_id);
      }

      os.close();
      is.close();
      client.close();
      /*
       * out.close(); 
       * in.close();
       */
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

    private void MapTextView(Map<Character> map, PrintStream out) {
        // TODO
    }

  // }
}
